name: update-site
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update-registry
          ref: master
          repo: n3sdu/n3sdu.github.io
          token: ${{ secrets.WORKFLOW_TRIGGER_PAT }}
